#!/usr/bin/env python

import netrc
import odoorpc
import ssl
import sys
import urllib2
import yaml
import argparse

from ModelSyncer import ModelSyncer

parser = argparse.ArgumentParser()
parser.add_argument('yamlfile')
args = parser.parse_args()


with open(args.yamlfile, 'r') as file:
    _dict = yaml.load(file)
    _dict = [] if _dict is None else _dict
    source = _dict.get('source')
    target = _dict.get('target')

def odoo_login(odoo_instance):
    opener = False
    protocol = 'jsonrpc'

    if odoo_instance.get('ssl', None):
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        opener = urllib2.build_opener(urllib2.HTTPSHandler(context=ctx))
        protocol = 'jsonrpc+ssl'

    instance = odoorpc.ODOO(
        odoo_instance.get('host'),
        port=odoo_instance.get('port'),
        opener=opener,
        protocol=protocol
    )

    instance.login(
        odoo_instance.get('database'),
        odoo_instance.get('user'),
        odoo_instance.get('password')
    )

    return instance

source_odoo = odoo_login(source)
target_odoo = odoo_login(target)

instance = ModelSyncer(source_odoo, target_odoo)
models = source.get('models')
for model in models:
    instance.sync(model)


# TODO:
# 1. combine these login things into one function login(source_odoo), login(target_odoo)
# 2. get the list of models to sync from the yaml file
# 3. extra parameter PER MODEL: sync_dependencies: Boolean --> yes/no (if no, "dumb" sync of model)
# 4. extra parameter PER MODEL: exclude_fields: list --> exclude stupid stuff like 'stock.location'

