#!/usr/bin/env python

import argparse
import os
import sys
import yaml

from odoosync.ModelSyncer import ModelSyncer, SyncException


def helptext(host):
    print "In your $HOME/.netrc file place:"
    print "machine odoo.example.com login myuser password mypassword"
    sys.exit(0)


# Open YAML file
parser = argparse.ArgumentParser()
parser.add_argument('yamlfile')
args = parser.parse_args()
yamlfile = args.yamlfile
_struct = {}
with open(yamlfile, 'r') as _file:
    _struct = yaml.load(_file)

# Open timestamp file
timestampfile = os.path.splitext(yamlfile)[0] + '.timestamp'
_timestamps = {}
try:
    with open(timestampfile, 'r') as _file:
        _timestamps = yaml.load(_file)
except IOError:
    pass

# Sync
try:
    instance = ModelSyncer(_struct, _timestamps)
except SyncException as e:
    helptext(e.args[0])
instance.prepare()
instance.sync()
_timestamps = instance.get_new_timestamps()
if _timestamps:
    with open(timestampfile, 'w') as _file:
        yaml.dump(_timestamps, _file)

